### ISSUE TITLE
Game Crashes and needs to be force closed

### ISSUE THREAD

**Issue by jacksonkimball** [gbl/EasierVillagerTrading#18] opened 2020-09-14 22:12 UTC
So I had my inventory full with stone and was interacting with a mason, it wouldn't take the trade out of my inventory so I pulled a stack out and held it in stasis on my mouse and I clicked on the trade, and the game crashed on me and I had to force close Java. I can't locate the crash report. But it should be easy to replicate. Sorry I couldn't be of more help!

**Comment by jacksonkimball** [comment] 2020-09-14 22:14
[crash-2020-09-09_23.58.58-client.txt](https://github.com/gbl/EasierVillagerTrading/files/5221360/crash-2020-09-09_23.58.58-client.txt)
Found this crash report but I don't know if it is what you need

**Comment by gbl** [comment] 2020-09-15 06:02
I'm afraid the crash didn't happen to me when I tried. But it might have happened from my mod and another mod interfering with each other, so it wouldn't happen to me without the other mod.

The crash report you posted is from a different crash - it seems like you were trying to run the shulker box tooltip mod without having Fabric api installed, so it doesn't really help either.
But there might be other log files in the same place. Is there any of them that actually has the word "easiervillagertrading" in it? It would likely, but not neccesarily, be in one of the lines that start with "Caused by".

**Comment by jacksonkimball** [comment] 2020-09-16 01:11
I don't have any crash reports for this then... I had to force close it because it froze on me, My only thought is it could have been something with Mouse wheelie that could have caused the problem. I will try to get a crash report for it...

**Comment by jacksonkimball** [comment] 2020-09-16 23:38
So I took all of my mods out except for Fabric API and I am still getting the crash, I realized that I forgot to say that I was shift clicking and it crashed. I have replicated it three times in a row on multiplayer. And I was able to replicate it in single player too.  And for some weird reason it is not generating a crash report even though the launcher reopens and gives me the error code 0 which does't help me figure out the issue... I have even tried to record it but it isn't recording well... Upon further inspection just clicking on it while holding the stack of items doesn't crash the game only when you are pressing shift and click does it crash the game, and I have tried three times to get a crash report but it isn't generating one.

**Comment by gbl** [comment] 2020-09-17 07:47
I might have found something. When you click a trade, the mod does all the clicking to execute that trade "in the background". This includes moving items from your inventory to the upper trade part. Now, if you have items in your cursor stack, the sequence "click the inventory - click the trade input" doesn't move the whole stack from the inventory; instead, it just puts your cursor stack into the trade input. As a result, if your cursor stack has fewer items than what's needed for a trade, there won't be enough input items, so the trade won't execute at all. Catching the mod in an endless loop because the mod thinks there's still enough items to trade, but the trade not happening.

I fixed this in 1.5.3, forcing the cursor stack to be empty to initiate a trade at all, and not trying to execute more than 50 trades per Shift-click. The good news is it probably won't crash on you any more, but the bad news is you still can't hold items on your cursor to use the mod; I need the cursor item stack to be empty to do the background clicking that moves the items.

**Closed as completed by gbl** 2020-09-17 07:47 UTC
